services:
  store-user:
    image: mysql:8.0.32
    container_name: app-user-rdbms-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: user
      MYSQL_USER: user
      MYSQL_PASSWORD: database-user-password
    ports:
      - "6000:3306"
    volumes:
      - ./mysql/user-init.sql:/docker-entrypoint-initdb.d/init.sql
      - user-mysql-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  store-pay-readwrite:
    image: mysql:8.0.32
    container_name: app-pay-rdbms-readwrite-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pay
      MYSQL_USER: pay
      MYSQL_PASSWORD: database-pay-password
    ports:
      - "6001:3306"
    volumes:
      - ./mysql/pay-init.sql:/docker-entrypoint-initdb.d/init.sql
      - pay-mysql-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db:
    driver: local
  user-mysql-data: {}
  pay-mysql-data: {}
