services:
  apps:
    build:
      context: .
      dockerfile: Dockerfile
    image: techfin-gateway:1.0
    ports:
      - "8080:8080"
    networks:
      - internal

    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:8080/health"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  internal:
    driver: bridge