### 사용자 프로파일과 계정 정보 저장
POST http://localhost:8081/user/account/create
Content-Type: application/json
Accept: application/json

{
    "profile": {
        "name" : "test",
        "residentNumber" : "111111-1010101",
        "age" : 26,
        "address" : {
            "city" : "서울",
            "district" : "강동구",
            "street" : "도로명 주소",
            "postCode" : "우편번호",
            "detailed" : "상세주소"
        },
        "email" : "eotjd228@naver.com",
        "phone" : "010-1234-1234"
    },
    "credential" : {
        "userid" : "test1234",
        "password" : "Qwer123!!",
        "username" : "test"
    }
}

### 회원 정보 수정
PUT http://localhost:8081/user/account/edit
Content-Type: application/json
Accept: application/json

{
"profile": {
"name" : "test",
"residentNumber" : "111111-1010101",
"age" : 26,
"address" : {
"city" : "전라남도",
"district" : "나주시",
"street" : "도로명 주소",
"postCode" : "우편번호",
"detailed" : "상세주소"
},
"email" : "eotjd228@naver.com",
"phone" : "010-1234-1235"
},
"credential" : {
"userid" : "test1234",
"password" : "Qwer123!!",
"username" : "test"
}
}